version: "3.8"
services:
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: admin
#      MONGO_INITDB_ROOT_PASSWORD: admin
    env_file:
      - ./env/mongo.env
  backend:
    build: "./backend"
    image: "goals-backend"
    ports:
      - "80:80"
    volumes:
      - logs:/app/logs
      - ./backend:/app"
      - /app/node_modules
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb
  frontend:
    build: "./frontend"
    image: "goals-frontend"
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend
volumes:
  data:
  logs:
