apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
      tier: backend
  template:
    metadata: 
      labels:
        app: demo-app
        tier: backend
    spec: 
      containers:
        - name: kube-app
          image: chisomoguibe/kube-starter-app:v2
        # - name: ...
        #   image: ...
