apiVersion: v1
kind: Service
metadata:
    name: backend
spec:
    selector: 
    app: demo-app
    tier: backend
    ports:
        - protocol: 'TCP'
      port: 80
      targetPort: 8080
    # - protocol: 'TCP'
    #   port: 443
    #   targetPort: 443
    type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: demo-app-deployment
spec:
    replicas: 2
    selector:
    matchLabels:
        app: demo-app
        tier: backend
    template:
    metadata: 
        labels:
        app: demo-app
        tier: backend
    spec: 
        containers:
            - name: kube-app
          image: chisomoguibe/kube-starter-app:v2
        # - name: ...
        #   image: ...